name: Create Versioning PR

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    name: Create Versioning PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Node.js 21.x
        uses: actions/setup-node@v5
        with:
          node-version: 21

      - name: Install Dependencies
        run: npm install

      - name: Check for changes and create changeset
        id: check_for_changes
        run: |
          if [[ $(git diff --name-only HEAD^ HEAD) ]]; then
            echo "Changes detected, creating a patch changeset."
            npx changeset add --empty --patch -m "Automated patch release"
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .changeset
            git commit -m "Add automated patch changeset"
            git push
          else
            echo "No changes detected, skipping changeset creation."
          fi

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          title: "Version Packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
